services:
  - type: web
    name: saini-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app & python modules/main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER
        sync: false
      - key: CREDIT
        sync: false
      - key: AUTH_USERS
        sync: false
